package POJOS;

public enum Symptoms {
    TREMOR,
    SLOW_MOVEMENT,
    STIFF_MUSCLES,
    DIFFICULTY_WITH_BALANCE,
    SHUFFLING_WALK,
    SMALL_HANDWRITING,
    SOFT_VOICE,
    DIFFICULTY_SWALLOWING,
    CONSTIPATION,
    DIZZINESS_OR_FAINTING,
    SLEEP_PROBLEMS,
    DEPRESSION,
    ANXIETY,
    REDUCED_FACIAL_EXPRESSION,
    BLADDER_PROBLEMS
}
